package mk.ukim.finki.soa.accreditation.model.study_program.documents

internal enum class DocumentTypes {

    ACCREDITATION_REQUEST, // baranje do OA

    CORE_DOCUMENT_CONTENT,  // document content by template

    FACULTY_BOARD_APPROVAL_DECISION, // d1

    UNIVERSITY_SENATE_APPROVAL_DECISION, // D2

    TRUST_BOARD_OPINION, // D3

    PROFESSOR_SUBJECT_ACCEPTANCE_DECLARATION, // D4

    OTHER_UNIVERSITY_APPROVALS_FOR_PROFESSORS, // D5

    OTHER_FACULTY_APPROVALS_FOR_PROFESSORS, // D6

    SUBJECT_DETAILS, // P3

    PROFESSOR_DETAILS, // P4

    DIPLOMA_SUPPLEMENT, // P5

    LEGAL_DOCUMENTS_LINKS, // P6

    FACULTY_ACCREDITATION_DECISION, // P7 OA

    LEASE_AGREEMENTS, // P8

    PREVIOUS_STUDY_PROGRAM_ACCREDITATION_APPROVAL, // P9 - OA

    PREVIOUS_STUDY_PROGRAM_ACCREDITATION_DECISION,  // P9 - MON

    MERGED_ACCREDITATION_REQUEST_DOCUMENT,

    ACCREDITATION_BOARD_OBJECTIONS,

    ACCREDITATION_BOARD_OBJECTIONS_RESPONSE,

    ACCREDITATION_BOARD_STUDY_PROGRAM_ACCREDITATION_APPROVAL,

    FINAL_STUDY_PROGRAM_ACCREDITATION_DECISION

}